### PR TITLE
Updated for Laravel 6.0

### PR DESCRIPTION
**Pull request by jdanino**
Updated for Laravel 6.0

### CODE REVIEW

**Comment by slavarazum** [comment]
Hi, thanks for this PR.
Why minimum php version should be upped to 7.2?

**Comment by niekdemelker** [comment]
@slavarazum minimum version shouldn't be upped, when the minimum version is 7.2 laravel 5.8 cannot be a requirement anymore, so only adding laravel 6.0 should be enough.

**Comment by jdanino** [comment]
Thanks, you are right. I changed it to 7.1.3

**Comment by niekdemelker** [comment]
@slavarazum could you please merge this? That would be great.

**Comment by slavarazum** [comment]
Added comatibility in [3.2.0](https://github.com/froala/nova-froala-field/releases/tag/3.2.0) version. Dropped `laravel/framework` dependency from compose.json, because it unnecessary with `laravel/nova` dependency.

Let me know, if you will have any issues.

**Pull request closed without merging**
